#!/bin/bash
# Manual Deployment Helper for CentOS-Docker Agent

echo "🚀 System Trace Agent Deployment Helper"
echo "=================================="
echo "Target: 192.168.50.198 (centos-docker)"
echo ""

echo "📋 Step 1: Copy deployment scripts"
echo "-----------------------------------"
echo "Run these commands from your local machine:"
echo ""
echo "scp deploy_centos_docker_agent.sh root@192.168.50.198:/root/"
echo "scp fix_ntp_centos_docker.sh root@192.168.50.198:/root/"
echo ""

echo "📋 Step 2: Connect to centos-docker"
echo "-----------------------------------"
echo "ssh root@192.168.50.198"
echo ""

echo "📋 Step 3: Run NTP configuration"
echo "-----------------------------------"
echo "Once connected to centos-docker, run:"
echo "sudo ./fix_ntp_centos_docker.sh"
echo ""

echo "📋 Step 4: Deploy System Trace agent"
echo "-----------------------------------"
echo "sudo ./deploy_centos_docker_agent.sh"
echo ""

echo "📋 Step 5: Verify deployment"
echo "-----------------------------------"
echo "systemctl status snmpd"
echo "systemctl status ntpd"
echo "systemctl status system-trace-agent"
echo ""
echo "snmpwalk -v2c -c public localhost 1.3.6.1.2.1.1.1.0"
echo "ntpq -p"
echo "journalctl -u system-trace-agent -f"
echo ""

echo "📋 Step 6: Return to local machine"
echo "-----------------------------------"
echo "exit"
echo ""

echo "📋 Step 7: Check System Trace dashboard"
echo "-----------------------------------"
echo "Open: http://localhost:8001"
echo "Check Configuration page for SNMP status"
echo "Check Overview page for protocol health"
echo ""

echo "🎯 Expected Results:"
echo "-------------------"
echo "✅ SNMP: OK · centos-docker responding"
echo "✅ NTP: OK · Time synchronized"
echo "✅ Agent: OK · Metrics reporting"
echo ""

echo "📚 Documentation:"
echo "----------------"
echo "Full guide: docs/CENTOS_DOCKER_DEPLOYMENT.md"
echo "Status report: agent_status_report.json"
echo ""

echo "🔧 Troubleshooting:"
echo "------------------"
echo "If SNMP fails: check firewall (port 161)"
echo "If NTP fails: check network connectivity"
echo "If agent fails: check Python dependencies"
echo ""

echo "💡 Quick Test Commands (on centos-docker):"
echo "----------------------------------------"
echo "# Test SNMP"
echo "snmpwalk -v2c -c public localhost 1.3.6.1.2.1.1.1.0"
echo ""
echo "# Check services"
echo "systemctl status snmpd ntpd system-trace-agent"
echo ""
echo "# Check ports"
echo "netstat -ulnp | grep -E ':161|:123'"
echo ""
echo "# Check logs"
echo "journalctl -u snmpd -u ntpd -u system-trace-agent --since '1 minute ago'"
